#############################
## ~/.config/starship.toml ##
#############################

format = """
$os\
${custom.userhost_local}\
${custom.userhost_remote}\
$localip\
$shlvl\
$singularity\
$kubernetes\
$directory\
$vcsh\
$fossil_branch\
$fossil_metrics\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$hg_branch\
$pijul_channel\
$docker_context\
$package\
$c\
$cmake\
$cobol\
$daml\
$dart\
$deno\
$dotnet\
$elixir\
$elm\
$erlang\
$fennel\
$gleam\
$golang\
$guix_shell\
$haskell\
$haxe\
$helm\
$java\
$julia\
$kotlin\
$gradle\
$lua\
$nim\
$nodejs\
$ocaml\
$opa\
$perl\
$php\
$pulumi\
$purescript\
$python\
$quarto\
$raku\
$rlang\
$red\
$ruby\
$rust\
$scala\
$solidity\
$swift\
$terraform\
$typst\
$vlang\
$vagrant\
$zig\
$buf\
$nix_shell\
$conda\
$meson\
$spack\
$memory_usage\
$aws\
$gcloud\
$openstack\
$azure\
$nats\
$direnv\
$env_var\
$mise\
$crystal\
$custom\
$sudo\
$cmd_duration\
$status\
$line_break\
$jobs\
$battery\
$time\
$container\
$netns\
$shell\
$character"""

add_newline = true
palette = 'homebrew'

[palettes.homebrew]
white = '#FFFFFF'
blue = '#0000FF'
green = '#00FF00'
red = '#FF0000'
orange = '#FF7F00'
yellow = '#FFFF00'
teal = '#00FFFF'
purple = '#FF00FF'

[os]
disabled = false
style = 'bold teal'
format = '[$symbol]($style) '

[os.symbols]
Alpaquita = "îª¢ "
Alpine = "ïŒ€ "
AlmaLinux = "ïŒ "
Amazon = "ï‰° "
Android = "ï…» "
Arch = "ïŒƒ "
Artix = "ïŒŸ "
CachyOS = "ïŒƒ "
CentOS = "ïŒ„ "
Debian = "ïŒ† "
DragonFly = "îŠ "
Emscripten = "ïˆ… "
EndeavourOS = "ï†— "
Fedora = "ïŒŠ "
FreeBSD = "ïŒŒ "
Garuda = "ó°›“ "
Gentoo = "ïŒ "
HardenedBSD = "ó°Œ "
Illumos = "ó°ˆ¸ "
Kali = "ïŒ§ "
Linux = "ïŒš "
Mabox = "î¬© "
Macos = "ïŒ‚ "
Manjaro = "ïŒ’ "
Mariner = "ï‡ "
MidnightBSD = "ï†† "
Mint = "ïŒ "
NetBSD = "ï€¤ "
NixOS = "ïŒ“ "
Nobara = "ï€ "
OpenBSD = "ó°ˆº "
openSUSE = "ïŒ” "
OracleLinux = "ó°Œ· "
Pop = "ïŒª "
Raspbian = "ïŒ• "
Redhat = "ïŒ– "
RedHatEnterprise = "ïŒ– "
RockyLinux = "ïŒ« "
Redox = "ó°€˜ "
Solus = "ó° ³ "
SUSE = "ïŒ” "
Ubuntu = "ïŒ› "
Unknown = "ïˆ­ "
Void = "ïŒ® "
Windows = "ó°² "


[custom.userhost_local]
disabled = false
when = 'test -z "$SSH_TTY"'
command = 'echo "$USER@$HOST"'
style = "bold fg:purple"
format = '[$output]($style) ğŸ•¹ï¸ '

[custom.userhost_remote]
disabled = false
when = 'test -n "$SSH_TTY"'
command = 'echo "$USER@$HOST"'
style = "bold fg:blue"
format = '[$output]($style) ğŸŒ '

[directory]
home_symbol = "ï€•  "
read_only = " ó°Œ¾ "
style = 'bold fg:white'
format = '[in](white dimmed) [$path ]($style)'
truncation_length = 2
truncation_symbol = 'â€¦/'
truncate_to_repo = false

[directory.substitutions]
'Desktop' = ' ï„ˆ  '
'Documents' = ' ó°ˆ™ '
'Downloads' = ' ï€™  '
'Music' = ' ï€  '
'Pictures' = ' ï€¾  '
'Videos' = ' ï€½  '

[git_branch]
style = 'blue'
symbol = 'ï˜ '
truncation_length = 20
format = '[on](white dimmed) [$symbol$branch ]($style)'

[git_commit]
only_detached = true
tag_disabled = false
tag_symbol = 'ï€« '
commit_hash_length = 7
style = 'teal'
format = '[\($hash$tag\)]($style) '

[git_state]
style	= 'bold yellow'
format = '\([$state( $progress_current/$progress_total)]($style)\) '

[git_status]
conflicted = '[îœ§${count}](red) '
ahead = '[ï± ${count}](green)'
behind = '[ï³ ${count}](yellow)'
untracked = '[ï„¨${count}](purple) '
stashed = '[ó±§˜ ${count}](teal) '
modified = '[ï‘™ ${count}](orange) '
staged = '[ï† ${count}](teal) '
renamed = '[ï„ ${count}](orange) '
deleted = '[âœ˜${count}](red) '
diverged = '[ï± ${ahead_count}](green)[ï³ ${behind_count}](yellow)'
style = 'bold'
format = '([$all_status$ahead_behind]($style))'

[status]
symbol = 'ğŸ˜µâ€ğŸ’«'
not_executable_symbol = 'ğŸ˜‚'
not_found_symbol = 'ğŸ§'
sigint_symbol = 'ğŸ¥¸'
disabled = false
map_symbol = true
format = '$symbol '

[aws]
symbol = "ó°…Ÿ "
format = '[on](white dimmed) [$symbol($profile )(\($region\) )(\[$duration\] )]($style)'

[terraform]
symbol = "îšš "
format = 	'[via](white dimmed) [$symbol$workspace]($style) '

[kubernetes]
symbol = "î  "
format = '[$symbol$context( \($namespace\))]($style) [in](white dimmed) '

[buf]
symbol = "ï’ "
format = '[with](white dimmed) [$symbol($version )]($style)'

[memory_usage]
symbol = "ó°› "
format = '[via](white dimmed) $symbol [${ram}( | ${swap})]($style) '

[nix_shell]
symbol = "ïŒ“ "
format = 	'[via](white dimmed) [$symbol$state( \($name\))]($style) '

[package]
symbol = "ó°— "
format = '[is](white dimmed) [$symbol$version]($style) '

[bun]
symbol = "î¯ "
format = '[via](white dimmed) [$symbol($version )]($style)'

[c]
symbol = "î˜ "
format = '[via](white dimmed) [$symbol($version(-$name) )]($style)'

[cpp]
symbol = "î˜ "
format = '[via](white dimmed) [$symbol($version(-$name) )]($style)'

[cmake]
symbol = "î” "
format = '[via](white dimmed) [$symbol($version )]($style)'

[dart]
symbol = "î˜ "
format = '(via)[white dimmed] [$symbol($version )]($style)'

[deno]
symbol = "îŸ€ "
format = '[via](white dimmed) [$symbol($version )]($style)'

[docker_context]
symbol = "ïŒˆ "
format = '[via](white dimmed) [$symbol$context]($style) '

[elixir]
symbol = "î˜­ "
format = '[via](white dimmed) [$symbol($version \(OTP $otp_version\) )]($style)'

[erlang]
format = '[via](white dimmed) [$symbol($version )]($style)'

[golang]
symbol = "î˜§ "
format = '[via](white dimmed) [$symbol($version )]($style)'

[haskell]
symbol = "î· "
format = '[via](white dimmed) [$symbol($version )]($style)'

[java]
symbol = "î‰– "
format = '[via](white dimmed) [${symbol}(${version} )]($style)'

[kotlin]
symbol = "î˜´ "
format = '[via](white dimmed) [$symbol($version )]($style)'

[lua]
symbol = "î˜  "
format = '[via](white dimmed) [$symbol($version )]($style)'

[nodejs]
symbol = "î´ "
format = '[via](white dimmed) [$symbol($version )]($style)'

[ocaml]
symbol = "î™º "
format = '[via](white dimmed) [$symbol($version )(\($switch_indicator$switch_name\) )]($style)'

[perl]
symbol = "î™¾ "
format = 	'[via](white dimmed) [$symbol($version )]($style)'

[php]
symbol = "î˜ˆ "
format = '[via](white dimmed) [$symbol($version )]($style)'

[python]
symbol = "îˆµ "
format = '[via](white dimmed) [${symbol}${pyenv_prefix}(${version} )(\($virtualenv\) )]($style)'

[rlang]
symbol = "ó°Ÿ” "
format = '[via](white dimmed) [$symbol($version )]($style)'

[ruby]
symbol = "î‘ "
format = '[via](white dimmed) [$symbol($version )]($style)'

[rust]
symbol = "ó±˜— "
format = '[via](white dimmed) [$symbol($version )]($style)'

[scala]
symbol = "îœ· "
format = '[via](white dimmed) [${symbol}(${version} )]($style)'

[swift]
symbol = "î• "
format = '[via](white dimmed) [$symbol($version )]($style)'

[zig]
symbol = "îš© "
format = '[via](white dimmed) [$symbol($version )]($style)'



